var addedService = [
//{
//	name: '数据恢复',
//	 nameEn: 'aqfhgj',
//	 desc: '数据恢复',
//	 price: 1500,
//	 unit:'/帐套',
//	 btnValue:'申请',
//	 imgSrc: '../images/value-added-icon.png',
//	 imgSrcSmall: '../images/value-added-icon-48.png',
//	 imgOutStyle:'background-position:0 0;',
//	 imgOutStyleSmall:'background-position:0 0;',
//	 buyLink: '',
//	 detailsLink: '',
//	 productId: 21,
//	 info: null //产品信息，包括计算后的价格、到期时间等等
//},
{
	name: '套打设计',
	 nameEn: 'tdsj',
	 desc: '套打设计',
	 price: 200,
	 unit:'/张',
	 btnValue:'申请',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-64px 0;',
	 imgOutStyleSmall:'background-position:-48px 0;',
	 buyLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1',
	 detailsLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1',
	 productId: 101807,
	 info: null //产品信息，包括计算后的价格、到期时间等等
},{
	name: '产品培训',
	 nameEn: 'cppx',
	 desc: '产品培训',
	 price: 500,
	 unit:'/次起',
	 btnValue:'申请',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-192px 0;',
	 imgOutStyleSmall:'background-position:-144px 0;',
	 buyLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1',
	 detailsLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1',
	 productId: 101807,
	 info: null //产品信息，包括计算后的价格、到期时间等等
},{
	name: '专属顾问服务',
	 nameEn: 'zsgwfw',
	 desc: '专属顾问服务',
	 price: 200,
	 unit:'/月起',
	 btnValue:'申请',
	 linkType:'',
	 imgSrc: '../images/value-added-icon.png',
	 imgSrcSmall: '../images/value-added-icon-48.png',
	 imgOutStyle:'background-position:-256px 0;',
	 buyLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1',
	 detailsLink: 'http://amos1.taobao.com/msg.ww?v=2&uid=阳红燕&s=1', 
	 productId: 101807,
	 info: null //产品信息，包括计算后的价格、到期时间等等
}
//,{
//	name: '初始化服务',
//	 nameEn: 'cshfw',
//	 desc: '初始化服务',
//	 price: 500,
//	 unit:'元/账套起',
//	 btnValue:'免费',
//	 linkType:'setting-advancedSetting-right',
//	 imgSrc: '../images/value-added-icon.png',
//	 imgSrcSmall: '../images/value-added-icon-48.png',
//	 imgOutStyle:'background-position:-320px 0;',
//	 buyLink: '',
//	 detailsLink: '',
//	 productId: 101807,
//	 info: null //产品信息，包括计算后的价格、到期时间等等
//}
];